export const ALL_TRANSFER = 'ALL_TRANSFER'
export const WITHOUT_TRANSFER = 'WITHOUT_TRANSFER'
export const ONE_TRANSFER = 'ONE_TRANSFER'
export const TWO_TRANSFER = 'TWO_TRANSFER'
export const THREE_TRANSFER = 'THREE_TRANSFER'

export const CHEAPEST_VARIANT = 'CHEAPEST_VARIANT'
export const FASTEST_VARIANT = 'FASTEST_VARIANT'
export const OPTIMAL_VARIANT = 'OPTIMAL_VARIANT'

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'
export const FETCH_DATA_ALL_LOADED = 'FETCH_DATA_ALL_LOADED'

export const SHOW_MORE = 'SHOW_MORE'
